pipeline {
  agent any
  stages {
    stage('Clone Repository') {
      steps {
        git 'https://your-repository-url.git'
      }
    }
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t devops-node-app ./app'
      }
    }
    stage('Push to ECR') {
      steps {
        sh 'aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin your-account-id.dkr.ecr.your-region.amazonaws.com'
        sh 'docker tag devops-node-app:latest your-account-id.dkr.ecr.your-region.amazonaws.com/devops-node-app:latest'
        sh 'docker push your-account-id.dkr.ecr.your-region.amazonaws.com/devops-node-app:latest'
      }
    }
    stage('Deploy to EKS') {
      steps {
        dir('./terraform') {
          sh 'terraform init'
          sh 'terraform apply -auto-approve'
        }
      }
    }
  }
}
